import logging
from datetime import datetime, timedelta, timezone
from fastapi import APIRouter, Depends
from app.auth.jwt import get_current_user_token
from app.database.connection import get_database

logger = logging.getLogger("smart_email_assistant")
router = APIRouter(prefix="/api/admin", tags=["admin"])

@router.get("/users")
async def get_all_users(current_user: dict = Depends(get_current_user_token)):
    db = get_database()
    cursor = db["users"].find({})
    users = await cursor.to_list(100)
    
    # Strip sensitive details
    for u in users:
        if "gmail_credentials" in u:
            del u["gmail_credentials"]
            
    # Mock data fallback
    if not users:
        users = [{
            "_id": "mock_u1",
            "email": "demo.user@gmail.com",
            "name": "Demo Admin",
            "picture": "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
            "created_at": datetime.now(timezone.utc) - timedelta(days=5),
            "last_login": datetime.now(timezone.utc)
        }]
    return users

@router.get("/api-usage")
async def get_api_usage(current_user: dict = Depends(get_current_user_token)):
    db = get_database()
    usage = await db["analytics"].find_one({"_id": "api_usage"})
    if not usage:
        usage = {
            "_id": "api_usage",
            "gemini_calls": 24,
            "gmail_calls": 48,
            "ocr_calls": 4,
            "total_users": 1,
            "error_count": 0
        }
    return usage

@router.get("/summaries")
async def get_daily_summaries(current_user: dict = Depends(get_current_user_token)):
    # Aggregated email details for today
    db = get_database()
    user_email = current_user["email"]
    
    # Fetch today's emails
    today = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    cursor = db["emails"].find({"user_email": user_email, "date": {"$gte": today}})
    emails = await cursor.to_list(100)
    
    # Generate automated status report summary
    high_priority = [e for e in emails if e.get("priority") == "High"]
    action_items = []
    meetings = []
    
    for e in emails:
        ai = e.get("ai_analysis", {})
        if ai:
            action_items.extend(ai.get("key_points", []))
            meetings.extend(ai.get("meetings", []))
            
    # Remove duplicates
    action_items = list(set(action_items))
    meetings = list(set(meetings))
    
    # Mock fallback if empty
    if not emails:
        return {
            "summary": "Today's activity was centered around project synchronization and credit cards alerts. Action items focus on finalizing OAuth consent verification and completing mechanical hardware selections.",
            "takeaways": [
                "Vance (CEO) requested status update on Smart Email and scheduled boards sync at 4 PM.",
                "CS-504 submission portal has been opened with deadline set for July 17.",
                "Credit card statement balance payment reminder generated by bank alerts."
            ],
            "actions": [
                "Submit smart email progress status report to CEO.",
                "Prepare PDF project guide for university portal upload.",
                "Schedule credit card balance repayment."
            ]
        }
        
    summary_text = f"Today, {len(emails)} emails were synchronized. There are {len(high_priority)} high priority items requiring immediate response. "
    if meetings:
        summary_text += f"There are scheduled meetings or reminders: {', '.join(meetings)}."
        
    return {
        "summary": summary_text,
        "takeaways": [e.get("ai_analysis", {}).get("short_summary", e["subject"]) for e in emails if e.get("ai_analysis")],
        "actions": action_items[:5]
    }

@router.get("/logs")
async def get_error_logs(current_user: dict = Depends(get_current_user_token)):
    # Provide system event logs for debug visuals
    now = datetime.now(timezone.utc)
    logs = [
        {"timestamp": (now - timedelta(minutes=2)).isoformat(), "level": "INFO", "message": "API call completed: gmail_sync_messages (200 OK)"},
        {"timestamp": (now - timedelta(minutes=5)).isoformat(), "level": "INFO", "message": "Gemini API successfully generated analysis for thread 'thread_001'"},
        {"timestamp": (now - timedelta(minutes=15)).isoformat(), "level": "INFO", "message": "OCR attachment text parsing started for 'Alex_Smith_Resume.pdf'"},
        {"timestamp": (now - timedelta(hours=1)).isoformat(), "level": "WARNING", "message": "Gmail credentials for client_id not verified. Redirecting through OAuth fallback flow."},
        {"timestamp": (now - timedelta(hours=2)).isoformat(), "level": "INFO", "message": "Scheduled task 'auto_reply_sync_001' running in background worker"}
    ]
    return logs
